spring.application.name=webseclab
server.port=8080
server.forward-headers-strategy=native

# SSL Configuration
# server.ssl.enabled=true
# server.ssl.key-store=classpath:webseclab-keystore.p12
# server.ssl.key-store-password=secretpassword
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=WebSecLab Dev Certificate

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/webseclab;AUTO_SERVER=TRUE}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASS:}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.thymeleaf.cache=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
